version: "3.8"

services:
  # Service für die Realtime-App
  realtime-app:
    build: .
    container_name: realtime-app
    ports:
      - "3000:3000"  # Externer Port 3000 auf den Container-Port 3000 weiterleiten
    volumes:
      - .:/app  # Verzeichnis in den Container einbinden, falls du lokale Änderungen hast
    environment:
      - NODE_ENV=production  # Falls notwendig, für die richtige Konfiguration

  # Service für Compreface
  compreface:
    image: exadel/compreface:latest  # Nutze das offizielle Compreface Docker-Image
    container_name: compreface
    ports:
      - "8000:8000"  # Externer Port 8001 auf den Container-Port 8000 weiterleiten
    volumes:
      - ./data:/compreface/data  # Speichere Daten persistent auf dem Host